<?= $this->extend('layout/student_layout') ?>
<?= $this->section('title') ?>
    Terms And Conditions
<?= $this->endSection() ?>
<?= $this->section('content') ?>

<main role="main">
    <!-- Hero Section -->
    <section class="position-relative overflow-hidden">
        <div class="py-5" style="background: linear-gradient(135deg, #1ab79c 0%, #128f7a 50%, #0d6b5a 100%);">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center text-white py-4">
                        <div class="mb-3">
                            <i class="fas fa-file-contract fa-3x"></i>
                        </div>
                        <h1 class="display-4 fw-bold mb-3">Terms & Conditions</h1>
                        <p class="lead mb-0">Please read these terms carefully before using our services</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Quick Navigation -->
    <section class="py-3 bg-light border-bottom sticky-top" style="z-index: 100;">
        <div class="container">
            <div class="d-flex flex-wrap justify-content-center gap-2">
                <a href="#general" class="btn btn-sm btn-outline-primary">General</a>
                <a href="#services" class="btn btn-sm btn-outline-primary">Services</a>
                <a href="#registration" class="btn btn-sm btn-outline-primary">Registration</a>
                <a href="#payment" class="btn btn-sm btn-outline-primary">Payment</a>
                <a href="#user-obligations" class="btn btn-sm btn-outline-primary">User Obligations</a>
                <a href="#copyright" class="btn btn-sm btn-outline-primary">Copyright</a>
                <a href="#disclaimer" class="btn btn-sm btn-outline-primary">Disclaimer</a>
            </div>
        </div>
    </section>

    <!-- Content Section -->
    <section class="py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-10">
                    
                    <!-- Introduction Card -->
                    <div class="card border-0 shadow-lg mb-5" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <p class="lead text-muted">
                                www.mycsmtp.com is an online portal, owned by MY CS MTP, an organisation registered & incorporated in India, for imparting education in relation to preparation of Company Secretary Examination by providing the facility of Taking Tests, Preparation Modules, Study Material, MCQ application, Question Banks & many more.
                            </p>
                        </div>
                    </div>

                    <!-- General Terms -->
                    <div id="general" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #1ab79c 0%, #128f7a 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-info-circle text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #1ab79c;">General Terms</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>"www.mycsmtp.com" (hereinafter, the "Website") is owned and operated by MY CS MTP incorporated & registered in India.</p>
                                
                                <p>You are advised to read and understand these Terms carefully as moving past the home page, or using any of the services shall be taken to mean that you have read and agreed to all of the policies, which constitute a legally binding agreement between you and the website. These terms are to be read along with the Privacy Policy and any other policies on the website.</p>
                                
                                <p>This document is an electronic record published in accordance with the provisions of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the Rules and Regulations, Privacy Policy and Terms of Service for access or usage of the website and being generated by a computer system, it does not require any physical or digital signatures.</p>
                                
                                <p>For the purpose of these Terms of Use, along with any amendments to the same, and wherever the context so requires "You", "Your" or "User" refer to the person visiting, accessing, browsing through and/or using the Website at any point in time. The term "We", "Us", "Our" shall mean and refer to the website and/or the MY CS MTP, depending on the context.</p>
                                
                                <p>The headings of each section in this Agreement are only for the purpose of organising the various provisions under this Agreement in an orderly manner. These headings shall not be used by either party to interpret the provisions contained under them in any manner. Further, the headings have no legal or contractual value.</p>
                                
                                <div class="alert alert-warning mt-3" role="alert">
                                    <i class="fas fa-exclamation-triangle me-2"></i>
                                    <strong>Important:</strong> We hold the sole right to modify the Terms of Service without prior permission from you or providing notice to you. The relationship creates on you a duty to periodically check the Terms of Service and stay updated on its requirements. If you continue to use the Website or avail any of its services without registration following such change, this is deemed as consent by you to the so amended policies.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Services Overview -->
                    <div id="services" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #6f42c1 0%, #5a32a3 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-briefcase text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #6f42c1;">Services Overview</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>The Website is an online platform where users can gain access to Products & Services that help them to prepare for Company Secretary Examination. The User can sign up themselves online and then gain access to the test papers, question banks, Study Material & Other Services after paying the Subscription Money. The Services shall be unlocked based on the subscription package you bought.</p>
                            </div>
                        </div>
                    </div>

                    <!-- Registration -->
                    <div id="registration" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #fd7e14 0%, #e56b0a 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-user-plus text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #fd7e14;">Registration</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>To use the services provided on the website and make purchases, it is compulsory to Signup after registration and then have to Buy Subscription Package. A User can get himself registered after providing basic details.</p>
                                
                                <p>After getting registered you will be provided a User ID on your Email & Phone No via SMS. After that you have to sign up on the Website using that User ID and a Password of your choice fulfilling the required conditions of password pattern.</p>
                                
                                <p>At the time of registration, the MY CS MTP shall collect the following personally identifiable information about you:</p>
                                
                                <ul class="list-group list-group-flush mb-3">
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>Name – Full Name</li>
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>Email Address</li>
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>Mobile Phone Number</li>
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>REG No.</li>
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>Age</li>
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>Gender</li>
                                    <li class="list-group-item"><i class="fas fa-check text-success me-2"></i>Address & PIN Code</li>
                                </ul>
                                
                                <div class="alert alert-info" role="alert">
                                    <i class="fas fa-shield-alt me-2"></i>
                                    You are solely responsible for protecting the confidentiality of your username and password and any activity under the account will be deemed to have been done by you.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Security -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #dc3545 0%, #b02a37 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-lock text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0 text-danger">Security</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties.</p>
                                
                                <div class="alert alert-success" role="alert">
                                    <i class="fas fa-credit-card me-2"></i>
                                    The User's credit and debit card information is not received, stored by or retained by the Proprietorship / Website in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- License and Access -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #20c997 0%, #16a085 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-key text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #20c997;">License and Access</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>The MY CS MTP grants you a limited sub-license to access and make personal use of the Site, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of the MY CS MTP.</p>
                                
                                <p>Such limited sub-license does not include/permit any resale or commercial use of the Site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of the Site or its contents.</p>
                                
                                <div class="alert alert-danger" role="alert">
                                    <i class="fas fa-ban me-2"></i>
                                    You shall not attempt to gain unauthorized access to any portion or feature of the Site, or any other systems or networks connected to the Site or to any server, computer, network, or to any of the services offered on or through the Site, by hacking, 'password mining' or any other illegitimate means.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Communications -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #0dcaf0 0%, #0aa2c0 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-comments text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #0dcaf0;">Communications</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>By using this Website, it is deemed that you have consented to receiving calls, autodialed and/or pre-recorded message calls, e-mails, from us at any time with the use of the telephone number and e-mail address that has been provided by you for the use of this website which are subject to the Privacy Policy.</p>
                                
                                <p>The user agrees to receive promotional communication and newsletters from the Proprietorship and its partners. This includes contacting you through information received through other parties.</p>
                                
                                <div class="alert alert-info" role="alert">
                                    <i class="fas fa-envelope-open-text me-2"></i>
                                    The user can opt out from such communication and/or newsletters either by unsubscribing on the Website itself, or by contacting the customer services team and placing a request for unsubscribing by sending an email to <strong>support@mycsmtp.com</strong>.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Payment -->
                    <div id="payment" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #ffc107 0%, #e0a800 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-credit-card text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #ffc107;">Payment</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p class="fw-bold mb-3">The following payment options are available on the Website:</p>
                                
                                <div class="row g-3 mb-4">
                                    <div class="col-md-6">
                                        <div class="d-flex align-items-center p-3 bg-light rounded-3">
                                            <i class="fas fa-credit-card me-3 text-primary fs-4"></i>
                                            <span>Domestic & International Credit Cards (Visa, Master Card, Amex)</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="d-flex align-items-center p-3 bg-light rounded-3">
                                            <i class="fas fa-university me-3 text-primary fs-4"></i>
                                            <span>Net Banking / Direct Debit payments</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="d-flex align-items-center p-3 bg-light rounded-3">
                                            <i class="fas fa-wallet me-3 text-primary fs-4"></i>
                                            <span>Payment Wallets</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="d-flex align-items-center p-3 bg-light rounded-3">
                                            <i class="fas fa-money-bill-wave me-3 text-primary fs-4"></i>
                                            <span>Cash (where applicable)</span>
                                        </div>
                                    </div>
                                </div>
                                
                                <p>As prescribed by the financial institutions issuing the credit or debit cards affiliated with Visa / Master Card / Amex, the User will be required to submit his/her Name on Card, 16-digit card number, card expiry date and 3-digit CVV number while making an online transaction.</p>
                            </div>
                        </div>
                    </div>

                    <!-- User Obligations -->
                    <div id="user-obligations" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #6c757d 0%, #495057 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-user-check text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0 text-secondary">User Obligations</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p class="fw-bold">You are a restricted user of this website. You are bound not to:</p>
                                
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                        <i class="fas fa-times-circle text-danger me-2"></i>
                                        Cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from any information or software obtained from the website without prior permission.
                                    </li>
                                    <li class="list-group-item">
                                        <i class="fas fa-times-circle text-danger me-2"></i>
                                        Access (or attempt to access) the Website and/or the materials or Services by any means other than through the interface that is provided by the website.
                                    </li>
                                    <li class="list-group-item">
                                        <i class="fas fa-times-circle text-danger me-2"></i>
                                        Use deep-link, robot, spider or other automatic device, program, algorithm or methodology to access, acquire, copy or monitor any portion of the Website.
                                    </li>
                                    <li class="list-group-item">
                                        <i class="fas fa-times-circle text-danger me-2"></i>
                                        Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others.
                                    </li>
                                    <li class="list-group-item">
                                        <i class="fas fa-times-circle text-danger me-2"></i>
                                        Engage in any activity that interferes with or disrupts access to the Website or the Services.
                                    </li>
                                    <li class="list-group-item">
                                        <i class="fas fa-times-circle text-danger me-2"></i>
                                        Upload or distribute files that contain viruses, corrupted files, or any other similar software or programs.
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Copyright and Trademark -->
                    <div id="copyright" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #1ab79c 0%, #128f7a 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-copyright text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #1ab79c;">Copyright and Trademark</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>MY CS MTP, its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, images, content and other materials which appear on the Site.</p>
                                
                                <p>Access to or use of the Site does not confer and should not be considered as conferring upon anyone any license to the Proprietorship or any third party's intellectual property rights. All rights, including copyright, in and to the Site are owned by or licensed to the MY CS MTP.</p>
                                
                                <div class="alert alert-warning" role="alert">
                                    <i class="fas fa-exclamation-circle me-2"></i>
                                    Any use of the Site or its contents, including copying or storing it or them in whole or part is prohibited without the permission of the MY CS MTP.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Disclaimer of Warranties -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #dc3545 0%, #b02a37 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-exclamation-triangle text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0 text-danger">Disclaimer of Warranties and Liabilities</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>You expressly understand and agree that, to the maximum extent permitted by applicable law:</p>
                                
                                <ul class="list-unstyled">
                                    <li class="mb-2"><i class="fas fa-angle-right me-2 text-danger"></i>Your requirements will be met or that services provided will be uninterrupted, timely, secure or error-free;</li>
                                    <li class="mb-2"><i class="fas fa-angle-right me-2 text-danger"></i>Materials, information and results obtained will be effective, accurate or reliable;</li>
                                    <li class="mb-2"><i class="fas fa-angle-right me-2 text-danger"></i>Any errors or defects in the website, services or other materials will be corrected.</li>
                                </ul>
                                
                                <p>To the maximum extent permitted by applicable law, we will have no liability related to user content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws.</p>
                            </div>
                        </div>
                    </div>

                    <!-- Indemnification -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #6f42c1 0%, #5a32a3 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-gavel text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #6f42c1;">Indemnification and Limitation of Liability</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>You agree to indemnify, defend and hold harmless this website/Proprietorship including but not limited to its affiliate vendors, agents and employees from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by us.</p>
                                
                                <p>In no event shall MY CS MTP, its officers, directors, employees, partners or suppliers be liable to you, the vendor or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits.</p>
                            </div>
                        </div>
                    </div>

                    <!-- Termination -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #ffc107 0%, #e0a800 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-door-open text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #ffc107;">Termination</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>This User Agreement is effective unless and until terminated by either you or MY CS MTP. You may terminate this User Agreement at any time, provided that you discontinue any further use of the Website.</p>
                                
                                <p>The Proprietorship may terminate this User Agreement at any time and may do so immediately without notice, and accordingly deny you access to the Site. Such termination will be without any liability to the Proprietorship.</p>
                            </div>
                        </div>
                    </div>

                    <!-- Privacy -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #20c997 0%, #16a085 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-user-shield text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #20c997;">Privacy</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <p>We encourage you to read the Privacy Policy and to use the information it contains to make informed decisions regarding your personal information.</p>
                                
                                <p>Further, you acknowledge, consent and agree that we may access, preserve, and disclose information you provide to us at any stage during your use of the Website. Disclosures of information to Third Parties are further addressed in Our Privacy Policy.</p>
                                
                                <a href="<?= base_url() ?>privacy-policy" class="btn btn-outline-success mt-3">
                                    <i class="fas fa-file-alt me-2"></i>View Privacy Policy
                                </a>
                            </div>
                        </div>
                    </div>

                    <!-- Disclaimer Section -->
                    <div id="disclaimer" class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #0dcaf0 0%, #0aa2c0 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-info-circle text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0" style="color: #0dcaf0;">Important Disclaimer</h2>
                        </div>
                        
                        <div class="card border-0 shadow-lg" style="border-radius: 15px; border-left: 5px solid #0dcaf0 !important;">
                            <div class="card-body p-4 p-md-5">
                                <div class="alert alert-info mb-4" role="alert">
                                    <h4 class="alert-heading mb-3"><i class="fas fa-clipboard-check me-2"></i>Test Series Disclaimer</h4>
                                </div>
                                
                                <p>The test series we offer for CS students is a valuable resource designed to assist them in their preparation for the final exams at each level of their CS studies. These mock test papers are meticulously crafted to simulate the format and complexity of the actual exams, providing students with an opportunity to practice their knowledge and skills in a controlled environment.</p>
                                
                                <p>However, it is important to note that while we aim to provide relevant and challenging questions in our test papers, <strong>we cannot guarantee that any specific questions from our mock tests will be included in the final exams</strong>. The content of the final exams is determined by the academic institution or examination board, and our test series is not affiliated with or endorsed by them.</p>
                                
                                <p>Our primary goal is to help students enhance their understanding of the subject matter and improve their exam-taking abilities. The mock test papers are intended to be used as a supplementary study tool to complement students' existing study materials and strategies.</p>
                                
                                <div class="alert alert-warning mt-4" role="alert">
                                    <i class="fas fa-lightbulb me-2"></i>
                                    <strong>Note:</strong> By practicing with our test series, students can identify areas of strength and weakness, refine their problem-solving techniques, and gain confidence in their preparation. However, students should approach the test series as a supplementary resource and continue their comprehensive study regimen using various resources such as textbooks, class notes, and online materials.
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Miscellaneous -->
                    <div class="mb-5">
                        <div class="d-flex align-items-center mb-4">
                            <div class="icon-box me-3" style="width: 50px; height: 50px; background: linear-gradient(135deg, #6c757d 0%, #495057 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center;">
                                <i class="fas fa-random text-white fs-4"></i>
                            </div>
                            <h2 class="h3 fw-bold mb-0 text-secondary">Miscellaneous Provisions</h2>
                        </div>
                        
                        <div class="card border-0 shadow-sm" style="border-radius: 15px;">
                            <div class="card-body p-4">
                                <h5 class="fw-bold mb-3">Entire Agreement</h5>
                                <p>The terms and conditions set forth in this Section and any additional or different terms expressly agreed by Client and Service vendor shall constitute the entire agreement and understanding of Client and Service vendor with respect to each Service Contract.</p>
                                
                                <h5 class="fw-bold mb-3 mt-4">Technical Support</h5>
                                <p>Technical issues may require 7-10 business days for resolution following submission of a support ticket to the mycsmtp.com administration team.</p>
                                
                                <h5 class="fw-bold mb-3 mt-4">Waiver & Severability</h5>
                                <p>The failure of either party at any time to require performance of any provision of this Agreement in no manner shall affect such party's right at a later time to enforce the same.</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</main>

<style>
    /* Smooth Scroll */
    html {
        scroll-behavior: smooth;
    }
    
    /* Icon Box Animation */
    .icon-box {
        transition: all 0.3s ease;
    }
    
    .icon-box:hover {
        transform: scale(1.1) rotate(5deg);
    }
    
    /* Card Hover Effects */
    .card {
        transition: all 0.3s ease;
    }
    
    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 15px 30px rgba(0,0,0,0.1) !important;
    }
    
    /* List Group Items */
    .list-group-item {
        border-left: none;
        border-right: none;
        padding-left: 0;
        padding-right: 0;
    }
    
    .list-group-item:first-child {
        border-top: none;
    }
    
    .list-group-item:last-child {
        border-bottom: none;
    }
    
    /* Alert Styles */
    .alert {
        border-radius: 10px;
    }
    
    /* Navigation Buttons */
    .btn-outline-primary {
        color: #1ab79c;
        border-color: #1ab79c;
        transition: all 0.3s ease;
    }
    
    .btn-outline-primary:hover {
        background-color: #1ab79c;
        border-color: #1ab79c;
        color: white;
    }
    
    /* Responsive */
    @media (max-width: 768px) {
        .display-4 {
            font-size: 2rem;
        }
        
        .sticky-top {
            position: relative !important;
        }
        
        .card-body {
            padding: 1.5rem !important;
        }
    }
    
    /* Focus Styles */
    a:focus-visible,
    button:focus-visible {
        outline: 3px solid #1ab79c;
        outline-offset: 2px;
    }
</style>

<?= $this->endSection() ?>
